---
# YAML documents begin with the document separator ---
 
# The minus in YAML this indicates a list item.  The playbook contains a list
# of plays, with each play being a dictionary
-
 
  # Target: where our play will run and options it will run with
  hosts: centos1
  gather_facts: false
 
  # Variable: variables that will apply to the play, on all target systems
  vars:
    inline_dict:
      {inline_dict_key: This is an inline dictionary value}
 
  # Task: the list of tasks that will be executed within the playbook
  tasks:
    - name: Test named inline dictionary dictionary
      debug:
        msg: "{{ inline_dict }}"
 
    - name: Test named inline dictionary dictionary key value with dictionary dot notation
      debug:
        msg: "{{ inline_dict.inline_dict_key }}"
 
    - name: Test named inline dictionary dictionary key value with brackets notation
      debug:
        msg: "{{ inline_dict['inline_dict_key'] }}"
 
# Three dots indicate the end of a YAML document
...
