---
# YAML documents begin with the document separator ---
 
# The minus in YAML this indicates a list item.  The playbook contains a list
# of plays, with each play being a dictionary
-
 
  # Target: where our play will run and options it will run with
  hosts: centos1
  gather_facts: false
 
  # Variable: variables that will apply to the play, on all target systems
  vars_prompt:
    - name: username
      private: false
 
  # Task: the list of tasks that will be executed within the playbook
  tasks:
    - name: Test vars_prompt
      debug:
        msg: "{{ username }}"
 
# Three dots indicate the end of a YAML document
...
